version: '3.7'

services:
  app: 
    image: app_nest_rest:v1
    container_name: app_nest_rest
    build: .
    env_file: .env
    ports: 
      - 3002:3002
    depends_on:
      - mongodb
    restart: always
    networks:
      - ms_nestjs2

  mongodb: 
    image: mongo:latest
    container_name: mongodb_fl2
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes: 
      - mongodb:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - ms_nestjs2

volumes:
  mongodb:

networks:
  ms_nestjs2:

    